# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Execs < Formula
  desc ""
  homepage "https://github.com/t4kamura/execs"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/t4kamura/execs/releases/download/v0.0.1/execs_Darwin_x86_64.tar.gz"
      sha256 "492beee7aed53880f816343481d1640e796149a8f08cad25bb411cee59652299"

      def install
        bin.install "execs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/t4kamura/execs/releases/download/v0.0.1/execs_Darwin_arm64.tar.gz"
      sha256 "4d86154ecdeabfb1afab348a641a62efbdad07ca4f71343a7cb3cf33c562c74e"

      def install
        bin.install "execs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/t4kamura/execs/releases/download/v0.0.1/execs_Linux_arm64.tar.gz"
      sha256 "0c5c5be931c60c1b55374f9e499e62d54619eb44535fd8c8818ec11d65e37a8f"

      def install
        bin.install "execs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/t4kamura/execs/releases/download/v0.0.1/execs_Linux_x86_64.tar.gz"
      sha256 "e1a89787ecc29ec68489c32a41852fe8664e2629493045ec0b33eec84554fe07"

      def install
        bin.install "execs"
      end
    end
  end
end
